package com.yahobong.server.users.dto;

import lombok.Data;

@Data
public class FileDTO {
    private int fileNo;
    private int albumsNo;
    private String content;
    private int year;
    private int month;
    private int day;
    private boolean star; // boolean 타입으로 변경
    private String filePath;
    private String regDate;

    // Getters and setters generated by Lombok
    // 'getStar()' 추가 (boolean이므로 return 값은 0 또는 1이 아닌 true 또는 false)
    public boolean isStar() {
        return star;
    }
}
